### ISSUE TITLE
"vagrant up" does not complete successfully

### ISSUE THREAD

**Issue by cdtaylor51** [adafruit/Adafruit-Pi-Kernel-o-Matic#10]
I am trying to run the https://github.com/adafruit/Adafruit-Pi-Kernel-o-Matic on my laptop computer (Asus G75VW, W8.1 Pro, 16GB RAM, C:=256GB SSD, 750GB HHD, etc).

When I enter the command "vargrant up" this is what happens:

The guest machine entered and invalid state while waiting for it to boot. etc.

![vagrantupcmdscreen](https://cloud.githubusercontent.com/assets/7751386/6398656/afad1e92-bdb2-11e4-84b1-31f4da682954.JPG)

Then I try go to the VirtualBox Manager and see that the VM kernel_o_matic has been created and it is in the Powered Off state.  

![vbm](https://cloud.githubusercontent.com/assets/7751386/6398844/0f65d026-bdb4-11e4-823d-8c1808ace717.JPG)

I then try to startup the VM again and I get this:

![errormessage](https://cloud.githubusercontent.com/assets/7751386/6398663/b8595f9c-bdb2-11e4-889a-ef234bd12a0b.JPG)

Could you please help me to solve this issue?

**Comment by brennen** [comment]
Copied from #9:

This does ring a bell. Here's a relevant-looking [Stackoverflow result](https://stackoverflow.com/questions/5482223/vt-x-is-not-available-when-i-start-my-virtual-machine) for that error message, but let me look around a bit.

**Comment by toddtreece** [comment]
@cdtaylor51 were you able to get vagrant up to complete after reducing the cpus to 1?

**Comment by cdtaylor51** [comment]
Yes, but I was never able to change the number of CPUs from 1 to anything else.  What actually made tge difference  was setting the memory to 3157 or something like that.

Thanks for the hint.

Sent from my T-Mobile 4G LTE Device

<div>-------- Original message --------</div><div>From: Todd Treece <notifications@github.com> </div><div>Date:03/10/2015  7:28 PM  (GMT-06:00) </div><div>To: adafruit/Adafruit-Pi-Kernel-o-Matic <Adafruit-Pi-Kernel-o-Matic@noreply.github.com> </div><div>Cc: cdtaylor51 <cdtaylor51@hotmail.com> </div><div>Subject: Re: [Adafruit-Pi-Kernel-o-Matic] "vagrant up" does not complete successfully (#10) </div><div>
</div>

@cdtaylor51 were you able to get vagrant up to complete after reducing the cpus to 1?

---

**Comment by toddtreece** [comment]
ah ok. i'm going to close this one, but let us know if you have more issues with it. thanks for the update!
