### ISSUE TITLE
Unable to make backup link of 'piscreen-overlay.dtb' - dpkg fails on install.sh

### ISSUE THREAD

**Issue by phishstang65** [adafruit/Adafruit-Pi-Kernel-o-Matic#11]
After successfully building with the latest kernel using this command:

> > sudo adabuild

I copied and uncompressed the tarball on my Pi. I then ran rpi-update on the Pi, rebooted, cd'd into the tarball directory and ran:

> > sudo ./install.sh

It runs and about halfway through produces this error:
Unpacking replacement raspberrypi-bootloader ...
dpkg: error processing raspberrypi-bootloader_1.20150228-1_armhf.deb (--install):
 unable to make backup link of `./boot/overlays/piscreen-overlay.dtb' before installing new version: Operation not permitted

Then once complete, the last items printed are:
Errors were encountered while processing:
 raspberrypi-bootloader_1.20150228-1_armhf.deb
Error completing: dpkg

Any idea what's going on?

**Comment by toddtreece** [comment]
@phishstang65 i just pushed a fix to `adabuild` that should take care of that issue. please let us know if you are still seeing the issue after you pull and rebuild your kernel.
