### ISSUE TITLE
kernel does not use device-tree

### ISSUE THREAD

**Issue by ctc** [adafruit/Adafruit-Pi-Kernel-o-Matic#12]
python RPi.GPIO fails and there is no /proc/device-tree 

the kernel needs to be marked dt-aware with mkknlimg
V1:
replace "cp arch/arm/boot/Image $PKG_DIR/boot/kernel.img" with "/opt/rpi_tools/mkimage/mkknlimg arch/arm/boot/Image /$PKG_DIR/boot/kernel.img"
V2:
replace "cp arch/arm/boot/Image $PKG_DIR/boot/kernel.img" with "/opt/rpi_tools/mkimage/mkknlimg arch/arm/boot/Image /$PKG_DIR/boot/kernel7.img"

**Comment by toddtreece** [comment]
@ctc thanks!
