### ISSUE TITLE
add other size PiTFT dts's

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit-Pi-Kernel-o-Matic#13]
pitft28r-overlay.dts is good, now we also need to add pitft35r pitft28c and pitft22

**Comment by brennen** [comment]
I think this may just require a rebuild - added to repo on Friday, I
think.  Will have to double check.

**Comment by ladyada** [comment]
ok github wont let me attach the files. ill email them

**Comment by toddtreece** [comment]
added

**Comment by pssc** [comment]
Hi, where are the overlays I haven't been able to find them on github...

**Comment by toddtreece** [comment]
@pssc here are the details for compiling: https://learn.adafruit.com/raspberry-pi-kernel-o-matic/build-a-kernel#custom-pitft-builds

**Comment by pssc** [comment]
@toddtreece  github search, google and random browsing(had looked at master and hadn't realised about piftf branch) had failed me, I'd ended up extracting a copy from raspberrypi-bootloader_1.20150309-1_armhf.deb, Many thanks.
