### ISSUE TITLE
Error message shown when using branch rpi-4.0.y:

### ISSUE THREAD

**Issue by andrewsil1** [adafruit/Adafruit-Pi-Kernel-o-Matic#14]
Technically this may not be a kernel-o-matic bug, but I thought it was at least worth mentioning.
Using the stock VM and sending adabuild the "-b rpi-4.0.y" parameter to select a different branch from the Rpi github repo, git complains when setting the Raspberry Pi 1 build that "error: pathspec 'rpi-4.0.y' did not match any file(s) known to git."  Yet that branch is clearly visible from the github site.  As a result it's not clear whether it's actually checking out that branch or whether it's continuing to use the default.

I think I can solve this by manually recloning the right branches into the kernel_repos directories and restarting adabuild, but I'm curious if you can reproduce this issue.

**Comment by toddtreece** [comment]
fixed by 9cdcf2313ca30618b10188bed2f55ab22ef83b1f

i removed the clone depth since the cloned repos are cached now. the first build will take longer, but additional builds and switching branches will be much faster.
