### ISSUE TITLE
Rainbow

### ISSUE THREAD

**Issue by BruceWouaigne** [adafruit/Adafruit-Pi-Kernel-o-Matic#16]
Hey guys! Each time I build a kernel, when I restart the PI i'm getting stuck on a nice rainbow splash screen. Am I doing something wrong?

For the record I've tried:

Raspberry 2 with 4.1.y kernel
Raspberry 2 with 4.0.y kernel
Raspberry 1 B+ with 4.0.y kernel

Thanks.

**Comment by toddtreece** [comment]
@BruceWouaigne i'm guessing we are going to need to do some updating for 4.x.x

can you point me to the repo & branch you are trying to build?

**Comment by BruceWouaigne** [comment]
Well i'm using the default repo https://github.com/raspberrypi/linux.git which the main branch is rpi-4.0.y

And here is the 4.1.y https://github.com/raspberrypi/linux/tree/rpi-4.1.y

**Comment by brennen** [comment]
Hey @BruceWouaigne - does seem likely we're going to need to make some changes, but so far I haven't been able to reproduce this failure with 4.0.y; I'll try 4.1.y next.

Could you post the specific `adabuild` command you're using? I wonder if something might not be going on with your config.

**Comment by BruceWouaigne** [comment]
Sure @brennen, I used
`vagrant@vagrant-ubuntu-trusty-32:~$ sudo adabuild -b rpi-4.1.y`
and didn't make any config changes.

**Comment by brennen** [comment]
Thanks! I'm running one of those right now, so I'll see if anything crops up. To check a couple of other things:
- is this a fresh install of the Kernel-o-Matic, or one you've had around for a bit (i.e., used to build earlier versions)?
- you might try deleting `v1_saved_config` and `v2_saved_config` - I get the sense we've had problems in the past with config state persisting there.
- did you notice any especially weird-seeming compile-time warnings or errors?

I just remembered that the persistent rainbow test pattern probably means [the kernel itself isn't booting](https://www.raspberrypi.org/forums/viewtopic.php?t=55464), so there may be some other variables here. Any errors when installing the package? Tried more than one SD card?

**Comment by BruceWouaigne** [comment]
Thanks to you :)

Yes it's a totally fresh install, first time ever I use this (amazing) tool.
I didn't notice anything weird except that it is really fast (like 5-10min) I'm running it on a Mac Book Air (not that powerfull).

The only warning are at the end of the compilation:

```
  INSTALL sound/sound_firmware.ko
  INSTALL sound/usb/6fire/snd-usb-6fire.ko
  INSTALL sound/usb/caiaq/snd-usb-caiaq.ko
  INSTALL sound/usb/misc/snd-ua101.ko
  INSTALL sound/usb/snd-usb-audio.ko
  INSTALL sound/usb/snd-usbmidi-lib.ko
  DEPMOD  4.1.2-v7+
Version: Linux version 4.1.2-v7+ (root@vagrant-ubuntu-trusty-32) (gcc version 4.8.3 20140106 (prerelease) (crosstool-NG linaro-1.13.1-4.8-2014.01 - Linaro GCC 2013.11) ) #1 SMP P
REEMPT Fri Jul 24 12:47:00 UTC 2015
DT: y
DDT: n
283x: n
dpkg-architecture: warning: specified GNU system type arm-linux-gnueabihf does not match gcc system type i686-linux-gnu, try setting a correct CC environment variable
 dpkg-buildpackage -rfakeroot -d -us -uc -b -aarmhf
dpkg-buildpackage: source package raspberrypi-firmware
dpkg-buildpackage: source version 1.20150724-1
dpkg-buildpackage: source distribution UNRELEASED
dpkg-buildpackage: source changed by root <root@vagrant-ubuntu-trusty-32>
dpkg-architecture: warning: specified GNU system type arm-linux-gnueabihf does not match gcc system type i686-linux-gnu, try setting a correct CC environment variable
 dpkg-source --before-build raspberrypi-firmware_1.20150724
dpkg-buildpackage: host architecture armhf
dpkg-source: info: applying 0001-Add-vmcs.conf-file-to-be-installed.patch
dpkg-source: info: applying 0002-Add-udev-rule-for-dev-vchiq-permissions.patch
 fakeroot debian/rules clean
dh clean --with quilt
   dh_testdir
   dh_auto_clean
   dh_quilt_unpatch
Removing patch 0002-Add-udev-rule-for-dev-vchiq-permissions.patch
Removing lib/udev/rules.d/10-local-rpi.rules

Removing patch 0001-Add-vmcs.conf-file-to-be-installed.patch
Removing etc/ld.so.conf.d/00-vmcs.conf

No patches applied
   dh_clean
 debian/rules build
dh build --with quilt
   dh_testdir
   dh_quilt_patch
Applying patch 0001-Add-vmcs.conf-file-to-be-installed.patch
patching file etc/ld.so.conf.d/00-vmcs.conf

Applying patch 0002-Add-udev-rule-for-dev-vchiq-permissions.patch
patching file lib/udev/rules.d/10-local-rpi.rules

Now at patch 0002-Add-udev-rule-for-dev-vchiq-permissions.patch
   dh_auto_configure
   dh_auto_build
   dh_auto_test
 fakeroot debian/rules binary
dh binary --with quilt
   dh_auto_test
   dh_testroot
   dh_prep
   dh_auto_install
   dh_install
   dh_installdocs
   dh_installchangelogs
   dh_installmodules
   dh_perl
   dh_link
   dh_compress
   debian/rules override_dh_fixperms
make[1]: Entering directory `/tmp/tmp.r0OwB85efa/raspberrypi-firmware_1.20150724'
dh_fixperms
chown -R :users debian/libraspberrypi-doc/opt/vc/src/hello_pi
chmod -R g+w debian/libraspberrypi-doc/opt/vc/src/hello_pi
make[1]: Leaving directory `/tmp/tmp.r0OwB85efa/raspberrypi-firmware_1.20150724'
   debian/rules override_dh_strip
make[1]: Entering directory `/tmp/tmp.r0OwB85efa/raspberrypi-firmware_1.20150724'
# don't strip anything
make[1]: Leaving directory `/tmp/tmp.r0OwB85efa/raspberrypi-firmware_1.20150724'
   dh_makeshlibs
   debian/rules override_dh_shlibdeps
make[1]: Entering directory `/tmp/tmp.r0OwB85efa/raspberrypi-firmware_1.20150724'
# this is not happy on armhf, let's just skip it
make[1]: Leaving directory `/tmp/tmp.r0OwB85efa/raspberrypi-firmware_1.20150724'
   dh_installdeb
      dh_gencontrol
dpkg-gencontrol: warning: Depends field of package libraspberrypi0: unknown substitution variable ${shlibs:Depends}
   dh_md5sums
   dh_builddeb
dpkg-deb: building package `libraspberrypi0' in `../libraspberrypi0_1.20150724-1_armhf.deb'.
dpkg-deb: building package `libraspberrypi-dev' in `../libraspberrypi-dev_1.20150724-1_armhf.deb'.
dpkg-deb: building package `libraspberrypi-doc' in `../libraspberrypi-doc_1.20150724-1_armhf.deb'.
dpkg-deb: building package `libraspberrypi-bin' in `../libraspberrypi-bin_1.20150724-1_armhf.deb'.
dpkg-deb: building package `raspberrypi-bootloader' in `../raspberrypi-bootloader_1.20150724-1_armhf.deb'.
 dpkg-genchanges -b >../raspberrypi-firmware_1.20150724-1_armhf.changes
dpkg-genchanges: binary-only upload - not including any source code
 dpkg-source --after-build raspberrypi-firmware_1.20150724
dpkg-buildpackage: binary only upload (no source included)
THE custom_kernel_1.20150724-1.tar.gz ARCHIVE SHOULD NOW BE
AVAILABLE IN THE KERNEL-O-MATIC FOLDER ON YOUR HOST MACHINE
```

**Comment by brennen** [comment]
Yep, sure enough. I get similar warnings and can reproduce the rainbow screen for this.

It seems like for [raspberrypi/linux](https://github.com/raspberrypi/linux), rpi-4.0.y is in a buildable state and rpi-4.1.y isn't. I'm not sure whether this is just the state of that repo or there's something we need to fix in the Kernel-o-Matic scripts, but I'll figure that out for sure.

**Comment by brennen** [comment]
FWIW, we've now [got a build up](https://blog.adafruit.com/2015/09/08/an-updated-linux-kernel-for-the-raspberry-pi-pitft-users-read-this-one/) that's our handful of changes on top of the raspberrypi/linux rpi-4.1.y, so I'm reasonably confident that's in working shape.
