### ISSUE TITLE
Error to install

### ISSUE THREAD

**Issue by sabas1080** [adafruit/Adafruit-Pi-Kernel-o-Matic#17]
I have a error to install in Raspberry Pi B+ the kernel 4.2

./install.sh

Errors were encountered while processing:
 raspberrypi-bootloader_1.20151215-1_armhf.deb
Error completing: dpkg

Thanks

**Comment by avantol** [comment]
I see the same issue.

**Comment by toddtreece** [comment]
are you using:

```
$ sudo ./install.sh
```

**Comment by sabas1080** [comment]
Yes @toddtreece

**Comment by sabas1080** [comment]
New test in Raspberry Pi B+ with Jessie with kernel 4.2.y @toddtreece 

http://imgur.com/a/jymhe

Thanks

**Comment by sabas1080** [comment]
In my case the error was apparently from the compilation

`error: RPC failed; result=56, HTTP code = 200MiB | 153.00 KiB/s fatal: The remote end hung up unexpectedly fatal: early EOF fatal: index-pack failed`

Solution:
`git config --global http.postBuffer 524288000`

I'm in testing

**Comment by sabas1080** [comment]
The Error is for WiFi connection, im testting with cable

**Comment by sabas1080** [comment]
Error solved, thanks
