### ISSUE TITLE
Origin of package scripts?

### ISSUE THREAD

**Issue by lusitania** [adafruit/Adafruit-Pi-Kernel-o-Matic#2]
Who created scripts/package/? Is it the work of a 3rd party? Where is the LICENSE file? Why should we consider the scripts/package/boot/ files trustworthy?

Best,
L

**Comment by toddtreece** [comment]
@lusitania I had planned to pull in `scripts/package/boot/*` from https://github.com/raspberrypi/firmware/tree/master/boot, and possibly make the source of `/boot` configurable via options in `adabuild`, but I haven't had a chance to yet. I'll get that switched out.

The stuff in `scripts/package/DEBIAN` was extracted from an older .deb package of https://github.com/adafruit/adafruit-raspberrypi-linux.  I'll find out licence info and add it. Thanks for the feedback!

**Comment by lusitania** [comment]
Your welcome. It would be sad to see otherwise good work topple over licensing squabbles.

**Comment by toddtreece** [comment]
@lusitania the merge of #4 should address most of the concerns in this one

**Comment by lusitania** [comment]
Cool! I think this addresses all my issues.
