### ISSUE TITLE
"vagrant up" does not complete successfully

### ISSUE THREAD

**Issue by cdtaylor51** [adafruit/Adafruit-Pi-Kernel-o-Matic#9]
I am trying to run the https://github.com/adafruit/Adafruit-Pi-Kernel-o-Matic on my laptop computer (Asus G75VW, W8.1 Pro, 16GB RAM, C:=256GB SSD, 750GB HHD, etc).

When I enter the command vargrant up this is what happens:

![vagrantupcmdscreen](https://cloud.githubusercontent.com/assets/7751386/6398656/afad1e92-bdb2-11e4-84b1-31f4da682954.JPG)

Then I try to startup the VM in VirtualBox Manager and I get this:

![errormessage](https://cloud.githubusercontent.com/assets/7751386/6398663/b8595f9c-bdb2-11e4-889a-ef234bd12a0b.JPG)

Could you please help me to solve this issue?

**Comment by brennen** [comment]
This does ring a bell. Here's a relevant-looking [Stackoverflow result](https://stackoverflow.com/questions/5482223/vt-x-is-not-available-when-i-start-my-virtual-machine) for that error message, but let me look around a bit.

**Comment by brennen** [comment]
Moving to #10, which has a bit of additional info.

**Comment by cdtaylor51** [comment]
I have an Intel core i7 3610qm processor.  It supports VX-x but not VX-d.  I reduced the base memory to 3175 MB and the VM started but I am still having trouble getting "vagrant up" to run successfully.

Thanks for your help.

Sent from my T-Mobile 4G LTE Device

<div>-------- Original message --------</div><div>From: Brennen Bearnes <notifications@github.com> </div><div>Date:02/26/2015  12:35 PM  (GMT-06:00) </div><div>To: adafruit/Adafruit-Pi-Kernel-o-Matic <Adafruit-Pi-Kernel-o-Matic@noreply.github.com> </div><div>Cc: cdtaylor51 <cdtaylor51@hotmail.com> </div><div>Subject: Re: [Adafruit-Pi-Kernel-o-Matic] "vagrant up" does not complete successfully (#9) </div><div>
</div>

This does ring a bell. Here's a relevant-looking [Stackoverflow result](https://stackoverflow.com/questions/5482223/vt-x-is-not-available-when-i-start-my-virtual-machine) for that error message, but let me look around a bit.

---

**Comment by tdicola** [comment]
Oh try forcing the number of CPU cores to just 1.  Assuming you're on windows, open the Vagrantfile and change this line: https://github.com/adafruit/Adafruit-Pi-Kernel-o-Matic/blob/master/Vagrantfile#L27 to just set `cpus = 1`.  Save and try vagrant up again.
